/**
 * Language Context
 * Manages app language (Arabic/English)
 */
import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation keys (will be expanded)
const translations: Record<Language, Record<string, string>> = {
  en: {
    'app.name': 'Message to Mind',
    'landing.welcome': 'Welcome to Message to Mind',
    'landing.tagline': 'Advanced EEG Communication Platform for Healthcare',
    'landing.selectRole': 'Select your role to access the platform',
    'landing.admin': 'System Admin',
    'landing.specialist': 'Medical Specialist',
    'landing.patient': 'Patient',
    'landing.login': 'Login',
    'header.user': 'User',
    'header.brand': 'Natiqi',
    'header.tagline': 'Mind to Message',
    'login.welcome': 'Welcome',
    'login.subtitle.admin': 'Natiqi Admin Login',
    'login.subtitle.specialist': 'Natiqi Medical Login',
    'login.subtitle.recipient': 'Natiqi Recipient Login',
    'login.nationalIdLabel': 'National ID',
    'login.nationalIdPlaceholder': 'Enter your National ID',
    'login.passwordLabel': 'Password',
    'login.passwordPlaceholder': 'Enter your password',
    'login.forgotPassword': 'Forgot password?',
    'login.submit': 'Login',
    'login.signUpPrompt': "Don't have an account? Create one",
    'login.errorBothFields': 'Please enter both ID and password',
    'login.errorGeneric': 'Login failed. Please try again.',
    'login.verifyCode': 'Enter verification code',
    'forgotPassword.heading': 'Forgot Password?',
    'forgotPassword.instructions':
      'Enter your registered National ID to receive a verification code.',
    'forgotPassword.nationalIdLabel': 'Registered National ID',
    'forgotPassword.nationalIdPlaceholder': 'Enter your National ID',
    'forgotPassword.sendCode': 'Send verification code',
    'forgotPassword.backToLogin': 'Back to Login',
    'forgotPassword.errorEmpty': 'Please enter your National ID',
    'signup.subtitle': 'Enter your details to set up a new account.',
    'signup.fullNameLabel': 'Full Name',
    'signup.fullNamePlaceholder': 'Enter your full name',
    'signup.genderLabel': 'Gender',
    'signup.genderSelect': 'Select gender',
    'signup.genderMale': 'Male',
    'signup.genderFemale': 'Female',
    'signup.phoneLabel': 'Phone Number',
    'signup.phonePlaceholder': 'Enter your phone number',
    'signup.emailLabel': 'Email',
    'signup.emailPlaceholder': 'Enter your email',
    'signup.passwordPlaceholderCreate': 'Create a password',
    'signup.confirmPasswordLabel': 'Confirm Password',
    'signup.confirmPasswordPlaceholder': 'Confirm your password',
    'signup.createAccount': 'Create Account',
    'signup.backToLogin': 'Back to Login',
    'signup.errorFillAll': 'Please fill all fields.',
    'signup.errorPasswordMismatch': 'Passwords do not match.',
    'signup.errorGeneric': 'Registration failed. Please try again.',
    'signup.errorIdDuplicateHint':
      'That ID is already in the system from your first sign-up. You cannot register again. Use Login with the same National ID and the password from that first sign-up, then complete verification (tap "Enter verification code" on the login screen if you see a verify message).',
    'signup.confirmTitle': 'Create account',
    'signup.confirmMessage': 'This account will be registered as user.',
    'signup.confirmBack': 'Back',
    'signup.confirmProceed': 'Proceed',
    'verify.subtitle':
      'Enter the verification code we sent to enable your account.',
    'verify.devHintWithCode':
      'Dev only: your code is {code}. In production this would arrive by email or SMS.',
    'verify.devHintFlask':
      'Run the Flask backend on port 5000. With debug on, the code is printed in the terminal or returned after sign-up.',
    'verify.codeLabel': 'Verification Code',
    'verify.codePlaceholder': 'Enter the code',
    'verify.submit': 'Verify Account',
    'verify.resend': 'Resend code',
    'verify.backToLogin': 'Back to Login',
    'verify.errorMissingNationalId': 'Missing account ID. Go back and sign up again.',
    'verify.errorEmptyCode': 'Please enter the verification code.',
    'verify.successVerified': 'Account verified. You can now log in.',
    'verify.errorGeneric': 'Verification failed.',
    'verify.errorMissingNationalIdShort': 'Missing account ID.',
    'verify.errorResendFailed': 'Could not resend.',
    'verify.resendDevCodePrefix': ' (dev code: ',
    'verify.resendDevCodeClose': ')',
    'verify.resendCheckTerminal':
      'Check the Flask terminal for the code in debug mode.',

    // ── Admin: User Management ──
    'admin.userManagement': 'User Management',
    'admin.userManagement.subtitle': 'Manage system users and permissions',
    'admin.addUser': 'Add User',
    'admin.addNewUser': 'Add New User',
    'admin.addNewUser.hint': 'After creation, the success message includes the temporary password. Gender is stored on this account.',
    'admin.editUser': 'Edit User',
    'admin.editUser.subtitle': 'Editing: ',
    'admin.createUser': 'Create User',
    'admin.saveChanges': 'Save Changes',
    'admin.cancel': 'Cancel',
    'admin.delete': 'Delete',
    'admin.deleteConfirm': 'This cannot be undone.',
    'admin.form.name': 'Name',
    'admin.form.fullName': 'Full Name',
    'admin.form.email': 'Email',
    'admin.form.phone': 'Phone',
    'admin.form.phoneNumber': 'Phone Number',
    'admin.form.nationalId': 'National ID',
    'admin.form.gender': 'Gender',
    'admin.form.role': 'Role',
    'admin.form.status': 'Status',
    'admin.form.required': 'Required input.',
    'admin.form.emailHint': 'Must be valid and unique.',
    'admin.form.phoneHint': '10 digits, starts with 05.',
    'admin.form.nationalIdHint': '10-digit required.',
    'admin.form.genderHint': 'Saved on this account.',
    'admin.form.statusDefault': 'Active (default)',
    'admin.form.statusHint': 'Auto-set when creating a user.',
    'admin.form.requiredFields': 'Required fields: name, email, national ID, gender, role.',
    'admin.form.nationalIdReadonly': 'National ID and role cannot be changed.',
    'admin.form.cannotChange': 'Cannot be changed',
    'admin.table.id': 'ID',
    'admin.table.name': 'Name',
    'admin.table.email': 'Email',
    'admin.table.role': 'Role',
    'admin.table.gender': 'Gender',
    'admin.table.status': 'Status',
    'admin.table.actions': 'Actions',

    // ── Admin: Deployed Model ──
    'admin.deployedModel': 'Deployed Model',
    'admin.deployedModel.hint': 'Record the production decoder: display name, version, and when it was last trained.',
    'admin.modelArtifact': 'Model Artifact',
    'admin.modelArtifact.checking': 'Checking Saved_Model…',
    'admin.modelArtifact.found': 'Found',
    'admin.modelArtifact.missing': 'Missing',
    'admin.model.currentName': 'Current Model Name',
    'admin.model.version': 'Version',
    'admin.model.trainingAccuracy': 'Training Accuracy (%)',
    'admin.model.saving': 'Saving…',
    'admin.model.saveInfo': 'Save Model Info',
    'admin.model.quickTest': 'Quick Inference Test',
    'admin.model.quickTest.hint': 'Sends a demo 14×128 window to POST /ml/predict-window and displays the result.',
    'admin.model.running': 'Running…',
    'admin.model.runTest': 'Run test inference',
    'admin.model.loading': 'Loading…',

    // ── Admin: System Logs ──
    'admin.systemLogs': 'System Logs',
    'admin.systemLogs.subtitle': 'Recent admin and specialist actions',
    'admin.systemLogs.empty': 'No logs yet. Actions will appear here automatically.',
    'admin.systemLogs.showMore': 'Show more',
    'admin.systemLogs.remaining': 'remaining',
    'admin.table.logId': 'Log ID',
    'admin.table.user': 'User',
    'admin.table.event': 'Event',
    'admin.table.timestamp': 'Timestamp',

    // ── Admin: Settings ──
    'admin.settings': 'Admin Settings',
    'admin.settings.subtitle': 'Control alerts, security, and backup policies',
    'admin.settings.appliesGlobally': 'Applies globally',
    'admin.profile': 'Profile',
    'admin.profile.changePassword': 'Change Password',
    'admin.profile.currentPassword': 'Current Password',
    'admin.profile.newPassword': 'New Password',
    'admin.profile.passwordHint': 'At least 8 characters',
    'admin.profile.updating': 'Updating…',
    'admin.profile.phoneHint': 'Shown on reports and audit logs',

    // ── Admin: System Health ──
    'admin.systemHealth': 'System Health',
    'admin.systemHealth.subtitle': 'Realtime Checks',
    'admin.activeModel': 'Active Model',
    'admin.activeModel.accuracy': 'Accuracy',
    'admin.activeModel.status': 'Status',

    // ── Admin: Patient Management ──
    'admin.patientManagement': 'Patient Management',
    'admin.patientManagement.subtitle': 'Add, edit, or suspend patient records',
    'admin.addPatient': 'Add Patient',
    'admin.addNewPatient': 'Add New Patient',
    'admin.addNewPatient.subtitle': 'Capture required patient details',
    'admin.editPatient': 'Edit Patient',
    'admin.form.roomNumber': 'Room Number',
    'admin.form.roomNumberHint': 'Unique ward or room ID (max 10 characters).',
    'admin.form.roomNumberEditHint': 'Must stay unique across patients.',
    'admin.form.patientName': 'Patient Name',
    'admin.form.dob': 'Date of Birth',
    'admin.form.dobHint': 'Type digits — dashes added automatically.',
    'admin.form.dobFormat': 'Format: YYYY-MM-DD',
    'admin.form.roleAuto': 'Patient (auto)',
    'admin.form.roleHint': 'Default user role: Patient.',
    'admin.form.deviceAuto': 'EEG Device Type',
    'admin.form.deviceValue': 'Emotiv EPOC X (auto)',
    'admin.form.deviceHint': 'Default EEG device.',
    'admin.form.statusAuto': 'Active (default)',
    'admin.form.statusAutoHint': 'Auto-set on creation.',
    'admin.form.patientRequired': 'Required: room number, name, National ID, DOB, gender. Role/device/status are auto.',
    'admin.form.patientEditReadonly': 'National ID cannot be changed. Room number must remain unique.',
    'admin.table.room': 'Room',
    'admin.table.dob': 'DOB',
    'admin.table.device': 'Device',

    // ── Admin: Sessions & Reports ──
    'admin.sessionManagement': 'Session Management',
    'admin.savedSessions': 'Saved Sessions',
    'admin.loadingSessions': 'Loading sessions…',
    'admin.reports': 'Reports',
    'admin.table.sessionId': 'ID',
    'admin.table.patient': 'Patient',
    'admin.table.topPredicted': 'Top Predicted',
    'admin.table.avgAcc': 'Avg Acc.',
    'admin.table.time': 'Time',
    'admin.table.reportId': 'Report ID',
    'admin.table.dateTime': 'Date & Time',
    'admin.table.topPredictedWord': 'Top Predicted Word',
    'admin.table.avgAccuracy': 'Avg Accuracy',
    'admin.table.export': 'Export',

    // ── Specialist ──
    'spec.dashboard': 'Specialist Dashboard',
    'spec.recentSessions': 'Recent Sessions',
    'spec.mySessions': 'My Sessions',
    'spec.settings': 'Settings',
    'spec.settings.subtitle': 'Manage your profile and account security',
    'spec.role': 'Clinician',
    'spec.profile': 'Professional Profile',
    'spec.profile.hint': 'Shown on reports and audit logs',
    'spec.device': 'Device: Emotiv EPOC X',
    'spec.channels': 'Channels: 14 | Battery: 82%',
    'spec.lastSync': 'Last sync: 45s ago',
    'spec.signalQuality': 'Signal quality: Stable',
    'spec.table.sessionId': 'Session ID',
    'spec.table.word': 'Word',
    'spec.table.accuracy': 'Accuracy',
    'spec.table.duration': 'Duration',

    // ── Patient ──
    'patient.settings': 'Settings',
    'patient.personalInfo': 'Personal Info',
    'patient.emailAddress': 'Email Address',
    'patient.phoneNumber': 'Phone Number',
    'patient.alertsSafety': 'Alerts & Safety',
    'patient.alertsSafety.loading': 'Loading preferences…',
    'patient.alertsSafety.hint': 'Toggle which words trigger the notification bell.',
    'patient.alertsSafety.minConfidence': 'Minimum Confidence (0–1)',
    'patient.alertsSafety.minConfidenceHint': 'Detections below this value are ignored for alerts.',
    'patient.alertsSafety.unavailable': 'Preferences unavailable.',
    'patient.changePassword': 'Change Password',
    'patient.currentPassword': 'Current Password',
    'patient.newPassword': 'New Password',
    'patient.passwordHint': 'At least 8 characters',
    'patient.updating': 'Updating…',
    'patient.eegActivity': 'EEG Session Activity',
    'patient.start': 'Start',
    'patient.running': 'Running…',
    'patient.stop': 'Stop',
    'patient.predictedWord': 'Predicted Word',
    'patient.tapToSwitch': 'Tap to switch between Arabic and English',
    'patient.calendar': 'Calendar',
    'patient.today': 'Today',
    'patient.sessionHistory': 'Session history',
    'patient.help': 'Help',
    'patient.pain': 'Pain',
    'patient.hungry': 'Hungry',
    'patient.thirsty': 'Thirsty',
    'patient.bathroom': 'Bathroom',

    // ── Session Report Modal ──
    'report.title': 'Session Report',
    'report.loading': 'Loading…',
    'report.sessionInfo': 'Session Info',
    'report.sessionId': 'Session ID',
    'report.start': 'Start',
    'report.end': 'End',
    'report.duration': 'Duration',
    'report.prediction': 'Prediction #',
    'report.predictedWord': 'Predicted Word',
    'report.time': 'Time',
    'report.confidence': 'Confidence',
    'report.mostPredictedWord': 'Most Predicted Word',
    'report.totalPredictions': 'Total Predictions',
    'report.avgConfidence': 'Avg Confidence',

    // ── Header ──
    'header.title': 'Natiqi',
    'header.slogan': 'Mind to Message',
    // ── Report missing keys ──
    'report.predictions': 'Predictions',
    'report.summary': 'Summary',

    // ── Admin Dashboard stat cards ──
    'admin.stat.totalUsers': 'Total Users',
    'admin.stat.allRoles': 'All Roles',
    'admin.stat.totalSessions': 'Total Sessions',
    'admin.stat.allTime': 'All Time',
    'admin.stat.modelAccuracy': 'Model Accuracy',
    'admin.stat.systemAlerts': 'System Alerts',
    'admin.stat.comingSoon': 'Coming Soon',
    'admin.reports.subtitle': 'Session summaries and exports',

    // ── Specialist stat cards & subtitles ──
    'spec.stat.assignedPatients': 'Assigned Patients',
    'spec.stat.fromYourList': 'From your list',
    'spec.stat.totalSessions': 'Total Sessions',
    'spec.stat.allTime': 'All time',
    'spec.stat.demoPreview': 'Demo preview',
    'spec.stat.modelAccuracy': 'Model Accuracy',
    'spec.sessions.subtitle': 'Create sessions (via inference) and review saved session history',
    'spec.sessions.loadedHint': 'Loaded from SQLite (EEGSession). New demo sessions use the integrated EEG model.',
    'spec.mySessions.subtitle': 'Past sessions with accuracy and duration',
    'spec.dashboard.subtitle': 'Monitor assigned patients and sessions',

    // ── Patient stat cards & subtitles ──
    'patient.stat.mostFrequentWord': 'Most Frequent Word',
    'patient.stat.last7daysDemo': 'Last 7 days · start live demo',
    'patient.stat.signalsDecoded': 'Signals Decoded',
    'patient.stat.last7days': 'Last 7 days',
    'patient.stat.alertsToday': 'Alerts Today',
    'patient.stat.confidence70': 'Confidence ≥ 70%',
    'patient.eegTrend': 'Live brain signal trend',
  },
  ar: {
    'app.name': 'رسالة للعقل',
    'landing.welcome': 'مرحباً بك في رسالة للعقل',
    'landing.tagline': 'منصة متقدمة للتواصل عبر تخطيط الدماغ للرعاية الصحية',
    'landing.selectRole': 'اختر دورك للوصول إلى المنصة',
    'landing.admin': 'مدير النظام',
    'landing.specialist': 'أخصائي طبي',
    'landing.patient': 'مريض',
    'landing.login': 'الدخول',
    'header.user': 'مستخدم',
    'header.brand': 'ناطيقي',
    'header.tagline': 'من الإشارة إلى العبارة',
    'login.welcome': 'أهلاً بك',
    'login.subtitle.admin': 'تسجيل دخول المشرف – ناطيقي',
    'login.subtitle.specialist': 'تسجيل دخول الطاقم الطبي – ناطيقي',
    'login.subtitle.recipient': 'تسجيل دخول المستفيد – ناطيقي',
    'login.nationalIdLabel': 'رقم الهوية',
    'login.nationalIdPlaceholder': 'أدخل رقم الهوية',
    'login.passwordLabel': 'كلمة المرور',
    'login.passwordPlaceholder': 'أدخل كلمة المرور',
    'login.forgotPassword': 'نسيت كلمة المرور؟',
    'login.submit': 'تسجيل الدخول',
    'login.signUpPrompt': 'ليس لديك حساب؟ أنشئ حساباً',
    'login.errorBothFields': 'الرجاء إدخال رقم الهوية وكلمة المرور',
    'login.errorGeneric': 'فشل تسجيل الدخول. حاول مرة أخرى.',
    'login.verifyCode': 'أدخل رمز التحقق',
    'forgotPassword.heading': 'نسيت كلمة المرور؟',
    'forgotPassword.instructions':
      'أدخل رقم الهوية المسجل لاستلام رمز التحقق.',
    'forgotPassword.nationalIdLabel': 'رقم الهوية المسجل',
    'forgotPassword.nationalIdPlaceholder': 'أدخل رقم الهوية',
    'forgotPassword.sendCode': 'إرسال رمز التحقق',
    'forgotPassword.backToLogin': 'العودة إلى تسجيل الدخول',
    'forgotPassword.errorEmpty': 'الرجاء إدخال رقم الهوية',
    'signup.subtitle': 'أدخل بياناتك لإنشاء حساب جديد.',
    'signup.fullNameLabel': 'الاسم الكامل',
    'signup.fullNamePlaceholder': 'أدخل اسمك الكامل',
    'signup.genderLabel': 'الجنس',
    'signup.genderSelect': 'اختر الجنس',
    'signup.genderMale': 'ذكر',
    'signup.genderFemale': 'أنثى',
    'signup.phoneLabel': 'رقم الجوال',
    'signup.phonePlaceholder': 'أدخل رقم الجوال',
    'signup.emailLabel': 'البريد الإلكتروني',
    'signup.emailPlaceholder': 'أدخل البريد الإلكتروني',
    'signup.passwordPlaceholderCreate': 'أنشئ كلمة مرور',
    'signup.confirmPasswordLabel': 'تأكيد كلمة المرور',
    'signup.confirmPasswordPlaceholder': 'أكد كلمة المرور',
    'signup.createAccount': 'إنشاء حساب',
    'signup.backToLogin': 'العودة إلى تسجيل الدخول',
    'signup.errorFillAll': 'الرجاء تعبئة جميع الحقول.',
    'signup.errorPasswordMismatch': 'كلمتا المرور غير متطابقتين.',
    'signup.errorGeneric': 'فشل التسجيل. حاول مرة أخرى.',
    'signup.errorIdDuplicateHint':
      'رقم الهوية مسجّل مسبقاً. لا يمكنك التسجيل مرة أخرى. استخدم تسجيل الدخول بنفس رقم الهوية وكلمة المرور من أول تسجيل، ثم أكمل التحقق (اضغط «أدخل رمز التحقق» في شاشة الدخول إن ظهرت رسالة التحقق).',
    'signup.confirmTitle': 'إنشاء حساب',
    'signup.confirmMessage': 'سيتم تسجيل هذا الحساب كمستخدم.',
    'signup.confirmBack': 'رجوع',
    'signup.confirmProceed': 'متابعة',
    'verify.subtitle': 'أدخل رمز التحقق الذي أرسلناه لتفعيل حسابك.',
    'verify.devHintWithCode':
      'للتجربة فقط: رمز التحقق هو {code}. في التطبيق الفعلي سيصلك عبر البريد الإلكتروني أو رسالة نصية.',
    'verify.devHintFlask':
      'شغّل خادم Flask على المنفذ 5000. مع وضع التصحيح، يُطبع الرمز في الطرفية أو يُعاد بعد التسجيل.',
    'verify.codeLabel': 'رمز التحقق',
    'verify.codePlaceholder': 'أدخل الرمز',
    'verify.submit': 'تفعيل الحساب',
    'verify.resend': 'إعادة إرسال الرمز',
    'verify.backToLogin': 'العودة إلى تسجيل الدخول',
    'verify.errorMissingNationalId': 'معرّف الحساب مفقود. ارجع وأكمل التسجيل من جديد.',
    'verify.errorEmptyCode': 'الرجاء إدخال رمز التحقق.',
    'verify.successVerified': 'تم التحقق من الحساب. يمكنك تسجيل الدخول الآن.',
    'verify.errorGeneric': 'فشل التحقق.',
    'verify.errorMissingNationalIdShort': 'معرّف الحساب مفقود.',
    'verify.errorResendFailed': 'تعذّر إعادة إرسال الرمز.',
    'verify.resendDevCodePrefix': ' (رمز التجربة: ',
    'verify.resendDevCodeClose': ')',
    'verify.resendCheckTerminal':
      'راجع نافذة Flask في وضع التصحيح لمعرفة الرمز.',

    // ── Admin: User Management ──
    'admin.userManagement': 'إدارة المستخدمين',
    'admin.userManagement.subtitle': 'إدارة مستخدمي النظام والصلاحيات',
    'admin.addUser': 'إضافة مستخدم',
    'admin.addNewUser': 'إضافة مستخدم جديد',
    'admin.addNewUser.hint': 'بعد الإنشاء، تظهر رسالة النجاح مع كلمة المرور المؤقتة. يتم حفظ الجنس في هذا الحساب.',
    'admin.editUser': 'تعديل المستخدم',
    'admin.editUser.subtitle': 'تعديل: ',
    'admin.createUser': 'إنشاء مستخدم',
    'admin.saveChanges': 'حفظ التغييرات',
    'admin.cancel': 'إلغاء',
    'admin.delete': 'حذف',
    'admin.deleteConfirm': 'لا يمكن التراجع عن هذا الإجراء.',
    'admin.form.name': 'الاسم',
    'admin.form.fullName': 'الاسم الكامل',
    'admin.form.email': 'البريد الإلكتروني',
    'admin.form.phone': 'رقم الجوال',
    'admin.form.phoneNumber': 'رقم الجوال',
    'admin.form.nationalId': 'رقم الهوية الوطنية',
    'admin.form.gender': 'الجنس',
    'admin.form.role': 'الدور',
    'admin.form.status': 'الحالة',
    'admin.form.required': 'حقل مطلوب.',
    'admin.form.emailHint': 'يجب أن يكون صحيحاً وفريداً.',
    'admin.form.phoneHint': '10 أرقام، تبدأ بـ 05.',
    'admin.form.nationalIdHint': 'مطلوب 10 أرقام.',
    'admin.form.genderHint': 'محفوظ في هذا الحساب.',
    'admin.form.statusDefault': 'نشط (افتراضي)',
    'admin.form.statusHint': 'يُضبط تلقائياً عند إنشاء المستخدم.',
    'admin.form.requiredFields': 'الحقول المطلوبة: الاسم، البريد، رقم الهوية، الجنس، الدور.',
    'admin.form.nationalIdReadonly': 'لا يمكن تغيير رقم الهوية أو الدور.',
    'admin.form.cannotChange': 'لا يمكن تغييره',
    'admin.table.id': 'المعرّف',
    'admin.table.name': 'الاسم',
    'admin.table.email': 'البريد',
    'admin.table.role': 'الدور',
    'admin.table.gender': 'الجنس',
    'admin.table.status': 'الحالة',
    'admin.table.actions': 'الإجراءات',

    // ── Admin: Deployed Model ──
    'admin.deployedModel': 'النموذج الحالي',
    'admin.deployedModel.hint': 'سجّل معلومات النموذج: الاسم، الإصدار، وتاريخ التدريب.',
    'admin.modelArtifact': 'ملف النموذج',
    'admin.modelArtifact.checking': 'جارٍ التحقق من النموذج المحفوظ…',
    'admin.modelArtifact.found': 'موجود',
    'admin.modelArtifact.missing': 'مفقود',
    'admin.model.currentName': 'اسم النموذج الحالي',
    'admin.model.version': 'الإصدار',
    'admin.model.trainingAccuracy': 'دقة التدريب (%)',
    'admin.model.saving': 'جارٍ الحفظ…',
    'admin.model.saveInfo': 'حفظ معلومات النموذج',
    'admin.model.quickTest': 'اختبار استنتاج سريع',
    'admin.model.quickTest.hint': 'يُرسل نافذة تجريبية 14×128 إلى /ml/predict-window ويعرض النتيجة.',
    'admin.model.running': 'جارٍ التشغيل…',
    'admin.model.runTest': 'تشغيل اختبار الاستنتاج',
    'admin.model.loading': 'جارٍ التحميل…',

    // ── Admin: System Logs ──
    'admin.systemLogs': 'سجلات النظام',
    'admin.systemLogs.subtitle': 'الإجراءات الأخيرة للمدير والمختصين',
    'admin.systemLogs.empty': 'لا توجد سجلات بعد. ستظهر الإجراءات هنا تلقائياً.',
    'admin.systemLogs.showMore': 'عرض المزيد',
    'admin.systemLogs.remaining': 'متبقية',
    'admin.table.logId': 'معرّف السجل',
    'admin.table.user': 'المستخدم',
    'admin.table.event': 'الحدث',
    'admin.table.timestamp': 'الوقت',

    // ── Admin: Settings ──
    'admin.settings': 'إعدادات المدير',
    'admin.settings.subtitle': 'التحكم في التنبيهات والأمان وسياسات النسخ الاحتياطي',
    'admin.settings.appliesGlobally': 'يُطبَّق على مستوى النظام',
    'admin.profile': 'الملف الشخصي',
    'admin.profile.changePassword': 'تغيير كلمة المرور',
    'admin.profile.currentPassword': 'كلمة المرور الحالية',
    'admin.profile.newPassword': 'كلمة المرور الجديدة',
    'admin.profile.passwordHint': '8 أحرف على الأقل',
    'admin.profile.updating': 'جارٍ التحديث…',
    'admin.profile.phoneHint': 'يظهر في التقارير وسجلات التدقيق',

    // ── Admin: System Health ──
    'admin.systemHealth': 'صحة النظام',
    'admin.systemHealth.subtitle': 'فحوصات فورية',
    'admin.activeModel': 'النموذج النشط',
    'admin.activeModel.accuracy': 'الدقة',
    'admin.activeModel.status': 'الحالة',

    // ── Admin: Patient Management ──
    'admin.patientManagement': 'إدارة المرضى',
    'admin.patientManagement.subtitle': 'إضافة سجلات المرضى أو تعديلها أو تعليقها',
    'admin.addPatient': 'إضافة مريض',
    'admin.addNewPatient': 'إضافة مريض جديد',
    'admin.addNewPatient.subtitle': 'أدخل بيانات المريض المطلوبة',
    'admin.editPatient': 'تعديل بيانات المريض',
    'admin.form.roomNumber': 'رقم الغرفة',
    'admin.form.roomNumberHint': 'معرّف فريد للجناح أو الغرفة (10 أحرف كحد أقصى).',
    'admin.form.roomNumberEditHint': 'يجب أن يبقى فريداً بين المرضى.',
    'admin.form.patientName': 'اسم المريض',
    'admin.form.dob': 'تاريخ الميلاد',
    'admin.form.dobHint': 'أدخل الأرقام — تُضاف الشرطات تلقائياً.',
    'admin.form.dobFormat': 'الصيغة: YYYY-MM-DD',
    'admin.form.roleAuto': 'مريض (تلقائي)',
    'admin.form.roleHint': 'الدور الافتراضي: مريض.',
    'admin.form.deviceAuto': 'نوع جهاز EEG',
    'admin.form.deviceValue': 'Emotiv EPOC X (تلقائي)',
    'admin.form.deviceHint': 'جهاز EEG الافتراضي.',
    'admin.form.statusAuto': 'نشط (افتراضي)',
    'admin.form.statusAutoHint': 'يُضبط تلقائياً عند الإنشاء.',
    'admin.form.patientRequired': 'المطلوب: رقم الغرفة، الاسم، رقم الهوية، تاريخ الميلاد، الجنس.',
    'admin.form.patientEditReadonly': 'لا يمكن تغيير رقم الهوية. رقم الغرفة يجب أن يبقى فريداً.',
    'admin.table.room': 'الغرفة',
    'admin.table.dob': 'تاريخ الميلاد',
    'admin.table.device': 'الجهاز',

    // ── Admin: Sessions & Reports ──
    'admin.sessionManagement': 'إدارة الجلسات',
    'admin.savedSessions': 'الجلسات المحفوظة',
    'admin.loadingSessions': 'جارٍ تحميل الجلسات…',
    'admin.reports': 'التقارير',
    'admin.table.sessionId': 'المعرّف',
    'admin.table.patient': 'المريض',
    'admin.table.topPredicted': 'الكلمة الأعلى',
    'admin.table.avgAcc': 'متوسط الدقة',
    'admin.table.time': 'الوقت',
    'admin.table.reportId': 'معرّف التقرير',
    'admin.table.dateTime': 'التاريخ والوقت',
    'admin.table.topPredictedWord': 'الكلمة الأعلى تردداً',
    'admin.table.avgAccuracy': 'متوسط الدقة',
    'admin.table.export': 'تصدير',

    // ── Specialist ──
    'spec.dashboard': 'لوحة تحكم الأخصائي',
    'spec.recentSessions': 'الجلسات الأخيرة',
    'spec.mySessions': 'جلساتي',
    'spec.settings': 'الإعدادات',
    'spec.settings.subtitle': 'إدارة ملفك الشخصي وأمان حسابك',
    'spec.role': 'أخصائي',
    'spec.profile': 'الملف المهني',
    'spec.profile.hint': 'يظهر في التقارير وسجلات التدقيق',
    'spec.device': 'الجهاز: Emotiv EPOC X',
    'spec.channels': 'القنوات: 14 | البطارية: 82%',
    'spec.lastSync': 'آخر مزامنة: منذ 45 ثانية',
    'spec.signalQuality': 'جودة الإشارة: مستقرة',
    'spec.table.sessionId': 'معرّف الجلسة',
    'spec.table.word': 'الكلمة',
    'spec.table.accuracy': 'الدقة',
    'spec.table.duration': 'المدة',

    // ── Patient ──
    'patient.settings': 'الإعدادات',
    'patient.personalInfo': 'المعلومات الشخصية',
    'patient.emailAddress': 'البريد الإلكتروني',
    'patient.phoneNumber': 'رقم الجوال',
    'patient.alertsSafety': 'التنبيهات والسلامة',
    'patient.alertsSafety.loading': 'جارٍ تحميل التفضيلات…',
    'patient.alertsSafety.hint': 'اختر الكلمات التي تُفعّل جرس الإشعارات.',
    'patient.alertsSafety.minConfidence': 'الحد الأدنى للثقة (0–1)',
    'patient.alertsSafety.minConfidenceHint': 'الاكتشافات الأدنى من هذه القيمة تُتجاهل للتنبيهات.',
    'patient.alertsSafety.unavailable': 'التفضيلات غير متاحة.',
    'patient.changePassword': 'تغيير كلمة المرور',
    'patient.currentPassword': 'كلمة المرور الحالية',
    'patient.newPassword': 'كلمة المرور الجديدة',
    'patient.passwordHint': '8 أحرف على الأقل',
    'patient.updating': 'جارٍ التحديث…',
    'patient.eegActivity': 'نشاط جلسة EEG',
    'patient.start': 'بدء',
    'patient.running': 'جارٍ التشغيل…',
    'patient.stop': 'إيقاف',
    'patient.predictedWord': 'الكلمة المتوقعة',
    'patient.tapToSwitch': 'اضغط للتبديل بين العربية والإنجليزية',
    'patient.calendar': 'التقويم',
    'patient.today': 'اليوم',
    'patient.sessionHistory': 'سجل الجلسات',
    'patient.help': 'مساعدة',
    'patient.pain': 'ألم',
    'patient.hungry': 'جوع',
    'patient.thirsty': 'عطش',
    'patient.bathroom': 'حمام',

    // ── Session Report Modal ──
    'report.title': 'تقرير الجلسة',
    'report.loading': 'جارٍ التحميل…',
    'report.sessionInfo': 'معلومات الجلسة',
    'report.sessionId': 'معرّف الجلسة',
    'report.start': 'البداية',
    'report.end': 'النهاية',
    'report.duration': 'المدة',
    'report.prediction': 'التنبؤ رقم ',
    'report.predictedWord': 'الكلمة المتوقعة',
    'report.time': 'الوقت',
    'report.confidence': 'الثقة',
    'report.mostPredictedWord': 'الكلمة الأكثر تنبؤاً',
    'report.totalPredictions': 'إجمالي التنبؤات',
    'report.avgConfidence': 'متوسط الثقة',

    // ── Header ──
    'header.title': 'ناطقي',
    'header.slogan': 'من الفكر إلى الكلمة',
    // ── Report missing keys ──
    'report.predictions': 'التنبؤات',
    'report.summary': 'الملخص',

    // ── Admin Dashboard stat cards ──
    'admin.stat.totalUsers': 'إجمالي المستخدمين',
    'admin.stat.allRoles': 'جميع الأدوار',
    'admin.stat.totalSessions': 'إجمالي الجلسات',
    'admin.stat.allTime': 'كل الوقت',
    'admin.stat.modelAccuracy': 'دقة النموذج',
    'admin.stat.systemAlerts': 'تنبيهات النظام',
    'admin.stat.comingSoon': 'قريباً',
    'admin.reports.subtitle': 'ملخصات الجلسات والتصدير',

    // ── Specialist stat cards & subtitles ──
    'spec.stat.assignedPatients': 'المرضى المعيّنون',
    'spec.stat.fromYourList': 'من قائمتك',
    'spec.stat.totalSessions': 'إجمالي الجلسات',
    'spec.stat.allTime': 'كل الوقت',
    'spec.stat.demoPreview': 'معاينة تجريبية',
    'spec.stat.modelAccuracy': 'دقة النموذج',
    'spec.sessions.subtitle': 'إنشاء الجلسات ومراجعة سجل الجلسات المحفوظة',
    'spec.sessions.loadedHint': 'محمّل من قاعدة البيانات. الجلسات التجريبية تستخدم النموذج المدمج.',
    'spec.mySessions.subtitle': 'الجلسات السابقة مع الدقة والمدة',
    'spec.dashboard.subtitle': 'مراقبة المرضى المعيّنين والجلسات',

    // ── Patient stat cards & subtitles ──
    'patient.stat.mostFrequentWord': 'الكلمة الأكثر تكراراً',
    'patient.stat.last7daysDemo': 'آخر 7 أيام · ابدأ العرض التجريبي',
    'patient.stat.signalsDecoded': 'الإشارات المفككة',
    'patient.stat.last7days': 'آخر 7 أيام',
    'patient.stat.alertsToday': 'تنبيهات اليوم',
    'patient.stat.confidence70': 'ثقة ≥ 70%',
    'patient.eegTrend': 'مسار الإشارة الدماغية المباشرة',
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        isRTL: language === 'ar',
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};